language: node_js

node_js: 
    - "0.10"
    - "0.11"
    - "0.12"
    - iojs

env: 
    global: 
        - secure: "®\x9EmÂ½\x90}\x87í=êÌl\x0E\x9C¿h\x01\aÈí·@¦\x9B¬\x9Fl+®&T\nK<\x15\x9Dã\x81øÛÅÌê\x17v{CÔs\N±Nba!mDÅÜ=jÜ}d\x06hó\x8B\rãÑ\x81\x90W\x9A\x89\e\x89JF\x1Aò£$Ø\x8Bæ¼ÿ[Þm'>\x8DZÓ`w=<G\x11/\x1CæZ:T|?8\x9F\x93\b\x96¢·^0\\\fÀWÄ²Æ"
